"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { format } from "date-fns";
import { ReportHeader } from "@/app/Components/reports/ReportHeader";
import { ReportFilterPanel } from "@/app/Components/reports/ReportFilterPanel";
import { FormattedDatePicker } from "@/app/Components/ui/formatted-date-picker";
import { Label } from "@/app/Components/ui/label";
import { Button } from "@/app/Components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow, } from "@/app/Components/ui/table";
import { Badge } from "@/app/Components/ui/badge";
import { Card, CardContent } from "@/app/Components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue, } from "@/app/Components/ui/select";
import { toast } from "sonner";
import { generateReportPDF, generateReportExcel, formatDataForExport } from "@/app/lib/export-utils";
export default function DailyTimeLogsReportPage() {
    const [page, setPage] = useState(1);
    const perPage = 50;
    // Filters
    const [dateFrom, setDateFrom] = useState(undefined);
    const [dateTo, setDateTo] = useState(undefined);
    const [autoGenerated, setAutoGenerated] = useState("all");
    const [customerId, setCustomerId] = useState("all");
    const [projectId, setProjectId] = useState("all");
    const [blockType, setBlockType] = useState("all");

    const { data: customers = [] } = useQuery({
        queryKey: ["clients"],
        queryFn: async () => {
            const res = await fetch("/api/clients");
            const data = await res.json();
            return Array.isArray(data) ? data : [];
        },
    });

    const { data: projects = [] } = useQuery({
        queryKey: ["projects", customerId],
        queryFn: async () => {
            const url = customerId !== "all" ? `/api/projects?customerId=${customerId}` : "/api/projects";
            const res = await fetch(url);
            const data = await res.json();
            return Array.isArray(data) ? data : [];
        },
    });

    const { data: reportData, isLoading: loading } = useQuery({
        queryKey: ["report-daily-time-logs", page, dateFrom?.toISOString(), dateTo?.toISOString(), autoGenerated, customerId, projectId, blockType],
        queryFn: async () => {
            const params = new URLSearchParams();
            params.append("page", page.toString());
            params.append("perPage", perPage.toString());
            if (dateFrom) params.append("dateFrom", dateFrom.toISOString());
            if (dateTo) params.append("dateTo", dateTo.toISOString());
            if (autoGenerated && autoGenerated !== "all") params.append("autoGenerated", autoGenerated);
            if (customerId !== "all") params.append("customerId", customerId);
            if (projectId !== "all") params.append("projectId", projectId);
            if (blockType !== "all") params.append("blockType", blockType);
            const res = await fetch(`/api/reports/daily-time-logs?${params.toString()}`);
            if (!res.ok) throw new Error("Failed to fetch report data");
            return res.json();
        },
    });

    const logs = reportData?.logs || [];
    const total = reportData?.total || 0;

    const clearFilters = () => {
        setDateFrom(undefined);
        setDateTo(undefined);
        setAutoGenerated("all");
        setCustomerId("all");
        setProjectId("all");
        setBlockType("all");
        setPage(1);
    };
    const getResourceLabel = (log) => {
        const bt = log.blockType || "VEHICLE";
        if (bt === "MATERIAL") return log.material?.name || log.resourceNameSnapshot || "—";
        if (bt === "LABOUR") return log.labour?.labourType || log.resourceNameSnapshot || "—";
        if (bt === "OPERATOR") return log.operator?.name || log.resourceNameSnapshot || "—";
        return log.vehicle ? `${log.vehicle.vehicleCode || log.vehicle.regNo} (${log.vehicle.brand?.name || ""} ${log.vehicle.model?.name || ""})`.trim() : log.resourceNameSnapshot || "—";
    };

    const exportColumns = [
        { key: "_date", header: "Date", format: (v) => format(new Date(v), "dd MMM yyyy") },
        { key: "_blockType", header: "Type" },
        { key: "_customer", header: "Customer" },
        { key: "_project", header: "Project" },
        { key: "_assignment", header: "Assignment" },
        { key: "_resource", header: "Resource" },
        { key: "_hours", header: "Hours" },
        { key: "_qty", header: "Qty" },
        { key: "_weekend", header: "Weekend" },
        { key: "_holiday", header: "Holiday" },
        { key: "_status", header: "Status" },
    ];

    const prepareExportData = () => logs.map(log => ({
        _date: log.date,
        _blockType: log.blockType || "VEHICLE",
        _customer: log.customer?.companyName || "Internal",
        _project: log.project?.name || "-",
        _assignment: log.assignment?.assignmentCode || "-",
        _resource: getResourceLabel(log),
        _hours: Number(log.workedHours || 0).toFixed(2),
        _qty: log.quantity != null ? String(log.quantity) : "-",
        _weekend: log.isWeekend ? "Yes" : "No",
        _holiday: log.isHoliday ? "Yes" : "No",
        _status: log.autoGenerated ? "Auto" : "Manual",
    }));

    const handleExportPDF = async () => {
        try {
            const { headers, rows } = formatDataForExport(prepareExportData(), exportColumns);
            generateReportPDF("Daily Time Log Report", headers, rows, `daily-time-logs-${format(new Date(), "yyyy-MM-dd")}`);
            toast.success("PDF exported successfully");
        }
        catch (error) {
            console.error(error);
            toast.error("Failed to export PDF");
        }
    };
    const handleExportExcel = async () => {
        try {
            const { headers, rows } = formatDataForExport(prepareExportData(), exportColumns);
            generateReportExcel("Daily Time Log Report", headers, rows, `daily-time-logs-${format(new Date(), "yyyy-MM-dd")}`);
            toast.success("Excel exported successfully");
        }
        catch (error) {
            console.error(error);
            toast.error("Failed to export Excel");
        }
    };
    return (<div className="p-6 space-y-6">
            <ReportHeader title="Daily Time Log Report" description="View all daily time logs with detailed filtering options" backHref="/reports" onExportPDF={handleExportPDF} onExportExcel={handleExportExcel}/>

            <ReportFilterPanel onClear={clearFilters}>
                <div>
                    <Label>From Date</Label>
                    <FormattedDatePicker value={dateFrom} onChange={setDateFrom} placeholder="Select start date"/>
                </div>
                <div>
                    <Label>To Date</Label>
                    <FormattedDatePicker value={dateTo} onChange={setDateTo} placeholder="Select end date"/>
                </div>
                <div>
                    <Label>Customer</Label>
                    <Select value={customerId} onValueChange={(val) => { setCustomerId(val); setProjectId("all"); }}>
                        <SelectTrigger>
                            <SelectValue placeholder="All"/>
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="all">All</SelectItem>
                            {customers.map((c) => (<SelectItem key={c.id} value={String(c.id)}>{c.companyName}</SelectItem>))}
                        </SelectContent>
                    </Select>
                </div>
                <div>
                    <Label>Project</Label>
                    <Select value={projectId} onValueChange={setProjectId}>
                        <SelectTrigger>
                            <SelectValue placeholder="All"/>
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="all">All</SelectItem>
                            {projects.map((p) => (<SelectItem key={p.id} value={String(p.id)}>{p.name}</SelectItem>))}
                        </SelectContent>
                    </Select>
                </div>
                <div>
                    <Label>Block Type</Label>
                    <Select value={blockType} onValueChange={setBlockType}>
                        <SelectTrigger>
                            <SelectValue placeholder="All"/>
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="all">All</SelectItem>
                            <SelectItem value="VEHICLE">Vehicle</SelectItem>
                            <SelectItem value="OPERATOR">Operator</SelectItem>
                            <SelectItem value="MATERIAL">Material</SelectItem>
                            <SelectItem value="LABOUR">Labour</SelectItem>
                        </SelectContent>
                    </Select>
                </div>
                <div>
                    <Label>Auto Generated</Label>
                    <Select value={autoGenerated} onValueChange={setAutoGenerated}>
                        <SelectTrigger>
                            <SelectValue placeholder="All"/>
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="all">All</SelectItem>
                            <SelectItem value="true">Yes</SelectItem>
                            <SelectItem value="false">No</SelectItem>
                        </SelectContent>
                    </Select>
                </div>
            </ReportFilterPanel>

            <Card className="border-slate-200/60 dark:border-slate-800/60 bg-white/50 dark:bg-slate-900/50 backdrop-blur-sm shadow-sm rounded-2xl overflow-hidden">
                <CardContent className="p-0">
                    <div className="rounded-2xl border border-slate-200/60 dark:border-slate-800/60 overflow-hidden">
                        <Table>
                            <TableHeader className="bg-slate-50/50 dark:bg-slate-900/50">
                                <TableRow className="hover:bg-transparent border-slate-200/60 dark:border-slate-800/60">
                                    <TableHead className="h-10">Date</TableHead>
                                    <TableHead className="h-10">Type</TableHead>
                                    <TableHead className="h-10">Customer</TableHead>
                                    <TableHead className="h-10">Project</TableHead>
                                    <TableHead className="h-10">Resource</TableHead>
                                    <TableHead className="h-10 text-center">Hours / Qty</TableHead>
                                    <TableHead className="h-10 text-center">Flags</TableHead>
                                    <TableHead className="h-10 text-center">Status</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {loading ? (<TableRow>
                                        <TableCell colSpan={8} className="h-24 text-center">
                                            Loading...
                                        </TableCell>
                                    </TableRow>) : logs.length === 0 ? (<TableRow>
                                        <TableCell colSpan={8} className="h-24 text-center">
                                            No logs found.
                                        </TableCell>
                                    </TableRow>) : (logs.map((log) => {
                                        const bt = log.blockType || "VEHICLE";
                                        const isQtyBased = bt === "MATERIAL" || bt === "LABOUR";
                                        return (<TableRow key={log.id} className="hover:bg-slate-50/50 dark:hover:bg-slate-800/50 border-slate-200/60 dark:border-slate-800/60">
                                            <TableCell className="w-[120px]">
                                                {format(new Date(log.date), "dd MMM yyyy")}
                                            </TableCell>
                                            <TableCell>
                                                <Badge variant="outline" className="text-xs">{bt}</Badge>
                                            </TableCell>
                                            <TableCell className="max-w-[150px] truncate">
                                                {log.customer?.companyName || <span className="text-muted-foreground italic text-xs">Internal</span>}
                                            </TableCell>
                                            <TableCell className="max-w-[150px] truncate">
                                                {log.project?.name || "-"}
                                            </TableCell>
                                            <TableCell className="max-w-[200px]">
                                                <span className="font-medium truncate">{getResourceLabel(log)}</span>
                                                {bt === "VEHICLE" && log.operator && (
                                                    <span className="text-xs text-muted-foreground block">{log.operator.name}</span>
                                                )}
                                            </TableCell>
                                            <TableCell className="text-center font-medium">
                                                {isQtyBased
                                                    ? (log.quantity != null ? `${log.quantity} units` : "—")
                                                    : Number(log.workedHours || 0).toFixed(2)
                                                }
                                            </TableCell>
                                            <TableCell className="text-center">
                                                <div className="flex justify-center gap-1">
                                                    {log.isWeekend && (<Badge variant="secondary" className="text-[10px] px-1 h-5">W</Badge>)}
                                                    {log.isHoliday && (<Badge variant="secondary" className="text-[10px] px-1 h-5 bg-blue-100 text-blue-700 hover:bg-blue-100">H</Badge>)}
                                                </div>
                                            </TableCell>
                                            <TableCell className="text-center">
                                                {log.autoGenerated ? (<Badge variant="secondary" className="text-xs">Auto</Badge>) : (<Badge variant="outline" className="text-xs">Manual</Badge>)}
                                            </TableCell>
                                        </TableRow>);
                                    }))}
                            </TableBody>
                        </Table>
                    </div>

                    <div className="mt-4 px-4 pb-4 flex items-center justify-between text-sm text-muted-foreground">
                        <div>
                            Showing {logs.length} of {total} entries
                        </div>
                        <div className="flex gap-2">
                            <Button variant="outline" size="sm" disabled={page === 1} onClick={() => setPage((p) => p - 1)}>
                                Previous
                            </Button>
                            <Button variant="outline" size="sm" disabled={logs.length < perPage} onClick={() => setPage((p) => p + 1)}>
                                Next
                            </Button>
                        </div>
                    </div>
                </CardContent>
            </Card>
        </div>);
}
