import { NextResponse } from "next/server";
import { dbTenant } from "@/app/lib/db";
import { getSession } from "@/app/lib/auth";
import { verifySessionPermission } from "@/app/lib/permissions";
import { logActivity } from "@/app/lib/logger";

export async function POST(request, { params }) {
    try {
        const session = await getSession();
        if (!session)
            return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
        const canEdit = await verifySessionPermission(session, "Assignment", "Edit");
        if (!canEdit)
            return NextResponse.json({ message: "Forbidden" }, { status: 403 });

        const { id, blockId } = await params;
        const assignmentId = parseInt(id);
        const bId = parseInt(blockId);

        // Find the block
        const [bRows] = await dbTenant(`SELECT * FROM \`assignment_blocks\` WHERE id = ? LIMIT 1`, [bId]);
        if (!bRows || bRows.length === 0)
            return NextResponse.json({ message: "Assignment Block not found" }, { status: 404 });

        const block = bRows[0];

        // Verify ownership
        if (block.assignmentId !== assignmentId)
            return NextResponse.json({ message: "Block does not belong to this assignment" }, { status: 400 });

        // Business rule: only ACTIVE blocks can be stopped
        if (block.status !== "ACTIVE")
            return NextResponse.json({ message: `Block is already ${block.status}` }, { status: 400 });

        const now = new Date();

        // Stop the block — set endDate to now, mark STOPPED, disable future auto-logs
        await dbTenant(`
            UPDATE \`assignment_blocks\`
            SET status = 'STOPPED', endDate = ?, enableAutoTimeLogs = 0, updatedAt = NOW()
            WHERE id = ?
        `, [now, bId]);

        // Clean up any future auto-generated time logs for this block
        await dbTenant(`
            DELETE FROM \`daily_time_logs\`
            WHERE assignmentBlockId = ? AND autoGenerated = 1 AND date > ?
        `, [bId, now]);

        const [updRows] = await dbTenant(`SELECT * FROM \`assignment_blocks\` WHERE id = ? LIMIT 1`, [bId]);
        await logActivity("ASSIGNMENT", assignmentId, "UPDATE", `Stopped vehicle block for vehicle ID ${block.vehicleId}`);

        return NextResponse.json({ message: "Vehicle block stopped successfully", block: updRows[0] });
    } catch (error) {
        console.error("Error stopping block:", error);
        return NextResponse.json({ message: "Error stopping block" }, { status: 500 });
    }
}
