import { NextResponse } from "next/server";
import { dbTenant } from "@/app/lib/db";
import { getSession } from "@/app/lib/auth";
import { verifySessionPermission } from "@/app/lib/permissions";

export async function GET(request) {
    try {
        const session = await getSession();
        if (!session) return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
        const hasPermission = await verifySessionPermission(session, "Reports", "View");
        if (!hasPermission) return NextResponse.json({ message: "Forbidden" }, { status: 403 });

        const { searchParams } = new URL(request.url);
        const page = parseInt(searchParams.get("page") || "1") || 1;
        const perPage = parseInt(searchParams.get("perPage") || "50") || 50;
        const dateFrom = searchParams.get("dateFrom");
        const dateTo = searchParams.get("dateTo");
        const customerId = searchParams.get("customerId");
        const projectId = searchParams.get("projectId");
        const vehicleId = searchParams.get("vehicleId");
        const operatorId = searchParams.get("operatorId");
        const autoGenerated = searchParams.get("autoGenerated");
        const blockType = searchParams.get("blockType");
        const isInternal = searchParams.get("isInternal");
        const offset = (page - 1) * perPage;

        let whereClause = "WHERE 1=1";
        const params = [];

        if (dateFrom) {
            whereClause += " AND d.date >= ?";
            params.push(`${dateFrom.substring(0, 10)} 00:00:00`);
        }
        if (dateTo) {
            whereClause += " AND d.date <= ?";
            params.push(`${dateTo.substring(0, 10)} 23:59:59.999`);
        }
        if (customerId) {
            whereClause += " AND d.customerId = ?";
            params.push(parseInt(customerId));
        }
        if (projectId) {
            whereClause += " AND d.projectId = ?";
            params.push(parseInt(projectId));
        }
        if (vehicleId) {
            whereClause += " AND d.vehicleId = ?";
            params.push(parseInt(vehicleId));
        }
        if (operatorId) {
            whereClause += " AND d.operatorId = ?";
            params.push(parseInt(operatorId));
        }
        if (autoGenerated !== null && autoGenerated !== undefined && autoGenerated !== "") {
            whereClause += " AND d.autoGenerated = ?";
            params.push(autoGenerated === "true" ? 1 : 0);
        }
        if (blockType && blockType !== "all") {
            whereClause += " AND d.blockType = ?";
            params.push(blockType);
        }
        if (isInternal === "true") {
            whereClause += " AND d.isInternal = 1";
        } else if (isInternal === "false") {
            whereClause += " AND d.isInternal = 0";
        }

        const [logs] = await dbTenant(`
            SELECT d.*,
                   c.companyName as customer_companyName,
                   p.name as project_name,
                   a.assignmentCode as assignment_assignmentCode,
                   v.vehicleCode as vehicle_vehicleCode, v.regNo as vehicle_regNo,
                   vb.name as vehicle_brand_name, vm.name as vehicle_model_name,
                   o.name as operator_name,
                   mat.name as material_name,
                   lab.labourType as labour_type
            FROM \`daily_time_logs\` d
            LEFT JOIN \`customers\` c ON c.id = d.customerId
            LEFT JOIN \`projects\` p ON p.id = d.projectId
            LEFT JOIN \`assignments\` a ON a.id = d.assignmentId
            LEFT JOIN \`vehicles\` v ON v.id = d.vehicleId
            LEFT JOIN \`vehicle_brands\` vb ON vb.id = v.brandId
            LEFT JOIN \`vehicle_models\` vm ON vm.id = v.modelId
            LEFT JOIN \`operators\` o ON o.id = d.operatorId
            LEFT JOIN \`materials\` mat ON mat.id = d.materialId
            LEFT JOIN \`labours\` lab ON lab.id = d.labourTypeId
            ${whereClause}
            ORDER BY d.date DESC
            LIMIT ${Number(perPage)} OFFSET ${Number(offset)}
        `, params);

        const [[{ total }]] = await dbTenant(`SELECT COUNT(*) as total FROM \`daily_time_logs\` d ${whereClause}`, params);

        const formattedLogs = (logs || []).map(l => ({
            ...l,
            customer: l.customer_companyName ? { companyName: l.customer_companyName } : null,
            project: l.project_name ? { name: l.project_name } : null,
            assignment: { assignmentCode: l.assignment_assignmentCode },
            vehicle: l.vehicle_vehicleCode ? {
                vehicleCode: l.vehicle_vehicleCode,
                regNo: l.vehicle_regNo,
                brand: { name: l.vehicle_brand_name },
                model: { name: l.vehicle_model_name }
            } : null,
            operator: l.operator_name ? { name: l.operator_name } : null,
            material: l.material_name ? { name: l.material_name } : null,
            labour: l.labour_type ? { labourType: l.labour_type } : null,
        }));

        return NextResponse.json({
            logs: formattedLogs,
            total,
            page,
            perPage,
            totalPages: Math.ceil(total / perPage),
        });
    } catch (error) {
        console.error("Error fetching daily time logs report:", error);
        return NextResponse.json({ message: "Error fetching report data" }, { status: 500 });
    }
}
